import { defineField, defineType } from "sanity";
import { Files } from "lucide-react";
import { orderRankField } from "@sanity/orderable-document-list";
import meta from "../blocks/shared/meta";

export default defineType({
  name: "page",
  type: "document",
  title: "Page",
  icon: Files,
  groups: [
    {
      name: "content",
      title: "Content",
    },
    {
      name: "seo",
      title: "SEO",
    },
    {
      name: "settings",
      title: "Settings",
    },
  ],
  fields: [
    defineField({ name: "title", type: "string", group: "content" }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "settings",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "blocks",
      type: "array",
      group: "content",
      of: [
        { type: "blog-4" },
        { type: "blog-7" },
        { type: "blog-13" },
        { type: "blog-14" },
        { type: "blog-16" },
        { type: "all-posts-4" },
        { type: "all-posts-7" },
        { type: "all-posts-13" },
        { type: "all-posts-14" },
        { type: "all-posts-16" },
        { type: "changelog-1" },
        { type: "changelog-2" },
        { type: "changelog-3" },
        { type: "changelog-5" },
        { type: "compare-1" },
        { type: "compare-2" },
        { type: "compare-4" },
        { type: "compare-5" },
        { type: "compare-6" },
        { type: "faq-1" },
        { type: "faq-5" },
        { type: "faq-8" },
        { type: "faq-9" },
        { type: "faq-14" },
        { type: "feature-1" },
        { type: "feature-3" },
        { type: "feature-12" },
        { type: "feature-15" },
        { type: "feature-66" },
        { type: "feature-117" },
        { type: "feature-157" },
        { type: "feature-202" },
        { type: "gallery-1" },
        { type: "gallery-3" },
        { type: "gallery-4" },
        { type: "gallery-8" },
        { type: "gallery-9" },
        { type: "gallery-10" },
        { type: "hero-12" },
        { type: "hero-13" },
        { type: "hero-25" },
        { type: "hero-57" },
        { type: "hero-85" },
        { type: "hero-160" },
        { type: "hero-174" },
        { type: "logos-1" },
        { type: "logos-2" },
        { type: "logos-4" },
        { type: "logos-9" },
        { type: "pricing-1" },
        { type: "pricing-2" },
        { type: "pricing-7" },
        { type: "pricing-9" },
        { type: "pricing-16" },
        { type: "section-header" },
        { type: "team-1" },
        { type: "team-2" },
        { type: "team-3" },
        { type: "team-4" },
        { type: "team-5" },
        { type: "team-6" },
        { type: "team-8" },
        { type: "timeline-3" },
        { type: "timeline-4" },
        { type: "timeline-5" },
        { type: "timeline-6" },
      ],
      options: {
        insertMenu: {
          groups: [
            {
              name: "blog",
              of: [
                "blog-4",
                "all-posts-4",
                "blog-7",
                "all-posts-7",
                "blog-13",
                "all-posts-13",
                "blog-14",
                "all-posts-14",
                "blog-16",
                "all-posts-16",
              ],
            },
            {
              name: "changelog",
              of: ["changelog-1", "changelog-2", "changelog-3", "changelog-5"],
            },
            {
              name: "compare",
              of: [
                "compare-1",
                "compare-2",
                "compare-4",
                "compare-5",
                "compare-6",
              ],
            },
            {
              name: "faq",
              of: ["faq-1", "faq-5", "faq-8", "faq-9", "faq-14"],
            },
            {
              name: "feature",
              of: [
                "feature-1",
                "feature-3",
                "feature-12",
                "feature-15",
                "feature-66",
                "feature-117",
                "feature-157",
                "feature-202",
              ],
            },
            {
              name: "gallery",
              of: [
                "gallery-1",
                "gallery-3",
                "gallery-4",
                "gallery-8",
                "gallery-9",
                "gallery-10",
              ],
            },
            {
              name: "hero",
              of: [
                "hero-12",
                "hero-13",
                "hero-25",
                "hero-57",
                "hero-85",
                "hero-160",
                "hero-174",
              ],
            },
            {
              name: "logos",
              of: ["logos-1", "logos-2", "logos-4", "logos-9"],
            },
            {
              name: "pricing",
              of: [
                "pricing-1",
                "pricing-2",
                "pricing-7",
                "pricing-9",
                "pricing-16",
              ],
            },
            {
              name: "section-header",
              of: ["section-header"],
            },
            {
              name: "team",
              of: [
                "team-1",
                "team-2",
                "team-3",
                "team-4",
                "team-5",
                "team-6",
                "team-8",
              ],
            },
            {
              name: "timeline",
              of: ["timeline-3", "timeline-4", "timeline-5", "timeline-6"],
            },
          ],
          views: [
            {
              name: "grid",
              previewImageUrl: (block) => `/static/images/preview/${block}.jpg`,
            },
            { name: "list" },
          ],
        },
      },
    }),
    meta,
    orderRankField({ type: "page" }),
  ],
});
